# FastSoftMaxGradOperation:
#     FastSoftMaxGradKernel:
#         ascend910b: true
# FastSoftMaxOperation:
#     FastSoftMaxKernel:
#         ascend910b: true
GatingOperation:
    GatingKernel:
        ascend310p: true
        ascend910b: true
GenAttentionMaskOperation:
    GenAttentionMaskKernel:
        ascend910b: true
KVCacheOperation:
    KVCacheNdDynamicBatchKernel:
        ascend910b: true
    KVCacheNdKernel:
        ascend910b: true
    KVCacheNzKernel:
        ascend310p: true
PadOperation:
    PadKernel:
        ascend310p: true
        ascend910b: true
PadWithHiddenStateOperation:
    PadWithHiddenStateKernel:
        ascend910b: true
PagedAttentionOperation:
    PagedAttentionDecoderNzMaskKernel:
        ascend310p: true
    PagedAttentionMaskNdKernel:
        ascend910b: true
ReshapeAndCacheOperation:
    ReshapeAndCacheCompressKernel:
        ascend910b: true
    ReshapeAndCacheNdKernel:
        ascend910b: true
    ReshapeAndCacheNzKernel:
        ascend310p: true
RopeGradOperation:
    RopeGradKernel:
        ascend910b: true
RopeOperation:
    RopeKernel:
        ascend310p: true
        ascend910b: true
# StridedBatchMatmulOperation:
#     StridedBatchMatmulKernel:
#         ascend910b: true
ToppsampleOperation:
    ToppsampleKernel:
        ascend310p: true
        ascend910b: true
UnpadFlashAttentionNzOperation:
    UnpadFlashAttentionNzDecoderKernel:
        ascend310p: true
    UnpadFlashAttentionNzEncoderKernel:
        ascend310p: true
UnpadFlashAttentionOperation:
    UnpadFlashAttentionBF16NdKernel:
        ascend910b: true
    UnpadFlashAttentionDecoderNdKernel:
        ascend910b: true
    UnpadFlashAttentionMlaBF16NdKernel:
        ascend910b: true
    UnpadFlashAttentionMlaDecoderNdKernel:
        ascend910b: true
    UnpadFlashAttentionMlaNdKernel:
        ascend910b: true
    UnpadFlashAttentionNdKernel:
        ascend910b: true
UnpadOperation:
    UnpadKernel:
        ascend310p: true
        ascend910b: true
UnpadWithHiddenStateOperation:
    UnpadWithHiddenStateKernel:
        ascend910b: true
